version: "3"
services:
  backend:
    build: ./backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "3000:3000"
      - "9229:9229"

  postgres:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bulingo
    volumes:
      - ./../../db-data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    volumes:
      - ./../../frontend-output/:/frontend/build

  android:
    build: ./mobile
    volumes:
      - ./../../android-output/:/mobile/bulingo/app/build/outputs/apk

  nginx:
   container_name: nginx
   image: nginx:1.13
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   - ./../../frontend-output:/frontend
   - ./../../android-output:/android
   depends_on:
   - backend
   - frontend
   - android