version: "3"
services:
  backend:
    env_file: ./backend/dev.env
    volumes:
      - ./backend:/backend
  postgres:
    volumes:
      - ./db-data:/var/lib/postgresql/data
  frontend:
    volumes:
      - ./frontend-output/:/frontend/build
  android:
    volumes:
      - ./android-output:/mobile/bulingo/app/build/outputs/apk